app:
  name: ui
  image:
    repository: 'onecx/onecx-remote-component-example-ui'
  routing:
    enabled: true
    path: /mfe/onecxRemoteComponentExampleUi/

  operator:
    # Microfrontend
    microfrontend:
      enabled: true
      specs:
        main:
          exposedModule: './OnecxRemoteComponentExampleUiModule'
          description: 'OneCX OnecxRemoteComponentExampleUi Module'
          note: 'OneCX OnecxRemoteComponentExampleUi UI module auto import via MF operator'
          type: MODULE
          technology: WEBCOMPONENTMODULE
          remoteName: onecx-remote-component-example-ui
          tagName: onecx-remote-component-example-ui-webcomponent
    # Permission
    # ACTION S11 Update permissions and roles: https://onecx.github.io/docs/nx-plugins/current/general/getting_started/search/update-permissions.html#action-11
    permission:
      enabled: true
      spec:
        permissions:
    # Keycloak
    keycloak:
      client:
        enabled: true
        spec:
          kcConfig:
            clientId: 'onecx-remote-component-example-ui'
# PIPE Config
