app:
  name: ui
  image:
    repository: 'onecx/onecx-remote-component-example-ui'
  routing:
    enabled: true
    path: /mfe/onecxRemoteComponentExampleUi/

  operator:
    # Microfrontend
    microfrontend:
      enabled: true
      specs:
        display-text:
          exposedModule: "./OneCXDisplayTextComponent"
          description: "Display Text Component"
          type: COMPONENT
          technology: WEBCOMPONENTMODULE
          remoteName: onecx-remote-component-example
          tagName: ocx-display-text-component
    # Permission
    # ACTION S11 Update permissions and roles: https://onecx.github.io/docs/nx-plugins/current/general/getting_started/search/update-permissions.html#action-11
    permission:
      enabled: true
      spec:
        permissions:
          TEXT:
            READ: Read text
    # Keycloak
    keycloak:
      client:
        enabled: true
        spec:
          kcConfig:
            clientId: 'onecx-remote-component-example-ui'
# PIPE Config
